// COMPONENTS
import Footer from "@/components/layout/Footer";
// STYLES
import "@/styles/globals.css";
// BUILT-IN PACKAGES
import Head from "next/head";
// HOOKS
import { useEffect, useState } from "react";
export default function App({ Component, pageProps }) {
  // DARKMODE STATES
  const [darkMode, setDarkMode] = useState(false);
  // TO SAVE AND CHECK IF DARKMODE IS ENABLED OR NOT
  useEffect(() => {
    if (JSON.parse(localStorage.getItem("isDarkMode") == null)) {
      localStorage.setItem("isDarkMode", JSON.stringify(darkMode));
    } else {
      let isDark = JSON.parse(localStorage.getItem("isDarkMode"));
      setDarkMode(isDark);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Chingal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className={darkMode ? "dark  overflow-hidden " : " overflow-hidden"}>
        <div className="w-full  bg-[#F3F8FC] bg-noise  bg-repeat dark:bg-[#0C132C]  min-h-[100vh] overflow-hidden ">
          <Component {...pageProps} setDarkMode={setDarkMode} />
          <Footer />
        </div>
      </div>
    </>
  );
}
