import { useEffect, useState } from "react";
import Head from "next/head";

import AppContext from "@/context/AppContext";
import "@/styles/globals.css";

export default function App({ Component, pageProps }) {
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    const theme = localStorage.getItem("isDarkMode");
    if (theme) {
      setDarkMode(JSON.parse(theme));
    } else {
      setDarkMode(darkMode);
    }
  }, []);
  useEffect(() => {
    localStorage.setItem("isDarkMode", darkMode);
  }, [darkMode]);

  return (
    <>
      <Head>
        <title>Chingal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={darkMode ? "dark  overflow-hidden " : " overflow-hidden"}>
        <div className="w-full  bg-[#F3F8FC] bg-noise  bg-repeat dark:bg-[#0C132C]  min-h-[100vh] overflow-hidden ">
          <AppContext.Provider value={{ darkMode, setDarkMode }}>
            <Component {...pageProps} />
          </AppContext.Provider>
        </div>
      </div>
    </>
  );
}
